2025-01-18 17:20:40,589 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2025-01-18 17:20:40,590 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Configure stats pid to 2600
2025-01-18 17:20:40,590 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Loading settings from C:\Users\abia0\.config\wandb\settings
2025-01-18 17:20:40,590 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Loading settings from C:\Users\abia0\OneDrive\Área de Trabalho\Projetos\Faculdade\topicos_especiais\Diabetes-Classification\Diabetes-Prediction\wandb\settings
2025-01-18 17:20:40,590 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-01-18 17:20:40,590 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-01-18 17:20:40,590 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-01-18 17:20:40,590 INFO    MainThread:2600 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-01-18 17:20:40,591 INFO    MainThread:2600 [wandb_init.py:_log_setup():533] Logging user logs to C:\Users\abia0\OneDrive\Área de Trabalho\Projetos\Faculdade\topicos_especiais\Diabetes-Classification\Diabetes-Prediction\wandb\run-20250118_172040-manif4ea\logs\debug.log
2025-01-18 17:20:40,592 INFO    MainThread:2600 [wandb_init.py:_log_setup():534] Logging internal logs to C:\Users\abia0\OneDrive\Área de Trabalho\Projetos\Faculdade\topicos_especiais\Diabetes-Classification\Diabetes-Prediction\wandb\run-20250118_172040-manif4ea\logs\debug-internal.log
2025-01-18 17:20:40,592 INFO    MainThread:2600 [wandb_init.py:init():619] calling init triggers
2025-01-18 17:20:40,592 INFO    MainThread:2600 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'model': 'diabetes_model', 'dataset': 'Diabetes dataset', 'metric': 'Accuracy'}
2025-01-18 17:20:40,592 INFO    MainThread:2600 [wandb_init.py:init():644] re-initializing run, found existing run on stack: 7lxzn1ih
2025-01-18 17:20:40,593 INFO    MainThread:2600 [wandb_run.py:_finish():2155] finishing run abiapegado014-ufrn/diabetes-classification/7lxzn1ih
2025-01-18 17:20:40,593 INFO    MainThread:2600 [jupyter.py:save_history():459] not saving jupyter history
2025-01-18 17:20:40,594 INFO    MainThread:2600 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-01-18 17:20:40,594 INFO    MainThread:2600 [wandb_init.py:_jupyter_teardown():461] cleaning up jupyter logic
2025-01-18 17:20:40,594 INFO    MainThread:2600 [wandb_run.py:_atexit_cleanup():2420] got exitcode: 0
2025-01-18 17:20:40,595 INFO    MainThread:2600 [wandb_run.py:_restore():2402] restore
2025-01-18 17:20:40,595 INFO    MainThread:2600 [wandb_run.py:_restore():2408] restore done
2025-01-18 17:20:43,089 INFO    MainThread:2600 [wandb_run.py:_footer_history_summary_info():3960] rendering history
2025-01-18 17:20:43,090 INFO    MainThread:2600 [wandb_run.py:_footer_history_summary_info():3992] rendering summary
2025-01-18 17:20:43,100 INFO    MainThread:2600 [wandb_run.py:_footer_sync_info():3921] logging synced files
2025-01-18 17:20:43,106 INFO    MainThread:2600 [wandb_init.py:init():669] starting backend
2025-01-18 17:20:43,106 INFO    MainThread:2600 [wandb_init.py:init():673] sending inform_init request
2025-01-18 17:20:43,111 INFO    MainThread:2600 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-01-18 17:20:43,112 INFO    MainThread:2600 [wandb_init.py:init():686] backend started and connected
2025-01-18 17:20:43,121 INFO    MainThread:2600 [wandb_run.py:_label_probe_notebook():1339] probe notebook
2025-01-18 17:20:43,122 INFO    MainThread:2600 [wandb_run.py:_label_probe_notebook():1349] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-01-18 17:20:43,122 INFO    MainThread:2600 [wandb_init.py:init():781] updated telemetry
2025-01-18 17:20:43,169 INFO    MainThread:2600 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2025-01-18 17:20:43,597 INFO    MainThread:2600 [wandb_init.py:init():867] starting run threads in backend
2025-01-18 17:20:43,871 INFO    MainThread:2600 [wandb_run.py:_console_start():2456] atexit reg
2025-01-18 17:20:43,871 INFO    MainThread:2600 [wandb_run.py:_redirect():2305] redirect: wrap_raw
2025-01-18 17:20:43,871 INFO    MainThread:2600 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-01-18 17:20:43,871 INFO    MainThread:2600 [wandb_run.py:_redirect():2395] Redirects installed.
2025-01-18 17:20:43,872 INFO    MainThread:2600 [wandb_init.py:init():911] run started, returning control to user process
2025-01-18 17:20:43,925 INFO    MainThread:2600 [wandb_run.py:_finish():2155] finishing run abiapegado014-ufrn/diabetes-classification/manif4ea
2025-01-18 17:20:43,926 INFO    MainThread:2600 [wandb_run.py:_atexit_cleanup():2420] got exitcode: 0
2025-01-18 17:20:43,926 INFO    MainThread:2600 [wandb_run.py:_restore():2402] restore
2025-01-18 17:20:43,926 INFO    MainThread:2600 [wandb_run.py:_restore():2408] restore done
2025-01-18 17:20:49,102 INFO    MainThread:2600 [wandb_run.py:_footer_history_summary_info():3960] rendering history
2025-01-18 17:20:49,102 INFO    MainThread:2600 [wandb_run.py:_footer_history_summary_info():3992] rendering summary
2025-01-18 17:20:49,114 INFO    MainThread:2600 [wandb_run.py:_footer_sync_info():3921] logging synced files
